/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lec4assignment1;
import java.awt.Color;
import java.awt.Graphics;
import java.util.Date;

/**
 *
 * @author Kareem
 */
public class NewJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setTitle("Lamp");
    }
    @Override
    public void paint (Graphics g){
        super.paint(g);
        
        g.setColor(Color.YELLOW);
        g.fillOval(150, 50, 100, 30);
        g.setColor(Color.BLACK);
        g.drawOval(150, 50, 100, 30);
        
        g.drawLine(150, 65, 130, 150);
        g.drawLine(250, 65, 270, 150);
        g.drawArc(130, 130, 140, 40, 0, -180);
        
       g.setColor(Color.YELLOW);
       g.fillOval(145, 100, 20, 40);
       g.setColor(Color.BLACK);
       g.drawOval(145, 100, 20, 40);
       g.setColor(Color.YELLOW);
       g.fillOval(185, 95, 30, 60);
       g.setColor(Color.BLACK);
       g.drawOval(185, 95, 30, 60);
       g.setColor(Color.YELLOW);
       g.fillOval(235, 100, 20, 40);
       g.setColor(Color.BLACK);
       g.drawOval(235, 100, 20, 40);
       
       g.drawLine(195, 170, 175, 230);
       g.drawLine(205, 170, 225, 230);
       
       g.drawRect(152, 230, 100, 20);


    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
