
package com.mycompany.paintproject;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;



public class PaintProject extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaintProject.class.getName());
    
    private ArrayList<GraphicShape> shapesList = new ArrayList<>();
    
    Color activeColor = ColorPalette.MAIN_RED; 
    String currentTool = "LINE";
    boolean isFilledMode = false;
    int pressX, pressY;
    
    JPanel controlPanel = new JPanel();
    JButton lineBtn = new JButton("Line");
    JButton rectBtn = new JButton("Rectangle");
    JButton ovalBtn = new JButton("Oval");
    JButton eraseBtn = new JButton("Eraser");
    JButton clearBtn = new JButton("Clear All");
    JCheckBox fillChk = new JCheckBox("Fill");
    
    JButton redBtn = new JButton("Red");
    JButton greenBtn = new JButton("Green");
    JButton blueBtn = new JButton("Blue");
    
    
    public PaintProject() {
        initComponents();
        setTitle("Paint Brush");
        setSize(1100, 750);
        this.setLayout(new BorderLayout());
        
        
        redBtn.setBackground(ColorPalette.MAIN_RED);
        redBtn.setForeground(Color.WHITE);
        greenBtn.setBackground(ColorPalette.MAIN_GREEN);
        greenBtn.setForeground(Color.WHITE);
        blueBtn.setBackground(ColorPalette.MAIN_BLUE);
        blueBtn.setForeground(Color.WHITE);
        
        controlPanel.setLayout(new FlowLayout());
        controlPanel.add(lineBtn);
        controlPanel.add(rectBtn);
        controlPanel.add(ovalBtn);
        controlPanel.add(eraseBtn);
        controlPanel.add(new JSeparator(SwingConstants.VERTICAL)); // فاصل
        controlPanel.add(redBtn);
        controlPanel.add(greenBtn);
        controlPanel.add(blueBtn);
        controlPanel.add(fillChk);
        controlPanel.add(clearBtn);
        
        this.add(controlPanel, BorderLayout.NORTH);
        
        redBtn.addActionListener(e -> activeColor = ColorPalette.MAIN_RED);
        greenBtn.addActionListener(e -> activeColor = ColorPalette.MAIN_GREEN);
        blueBtn.addActionListener(e -> activeColor = ColorPalette.MAIN_BLUE);
        
        lineBtn.addActionListener(e -> currentTool = "LINE");
        rectBtn.addActionListener(e -> currentTool = "RECT");
        ovalBtn.addActionListener(e -> currentTool = "OVAL");
        eraseBtn.addActionListener(e -> {
            currentTool = "ERASER";
            activeColor = ColorPalette.ERASER_COLOR;
        });
        
        fillChk.addItemListener(e -> isFilledMode = fillChk.isSelected());
        clearBtn.addActionListener(e -> { shapesList.clear(); repaint(); });
        
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                pressX = e.getX();
                pressY = e.getY();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                int releaseX = e.getX();
                int releaseY = e.getY();
                int w = Math.abs(releaseX - pressX);
                int h = Math.abs(releaseY - pressY);
                int x = Math.min(pressX, releaseX);
                int y = Math.min(pressY, releaseY);

                if (currentTool.equals("LINE")) {
                    shapesList.add(new Line(pressX, pressY, releaseX, releaseY, activeColor));
                } else if (currentTool.equals("RECT")) {
                    shapesList.add(new BoxArea(x, y, w, h, activeColor, isFilledMode));
                } else if (currentTool.equals("OVAL")) {
                    shapesList.add(new OvalArea(x, y, w, h, activeColor, isFilledMode));
                }
                repaint();
            }
        });

        this.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                if (currentTool.equals("ERASER")) {
                    shapesList.add(new BoxArea(e.getX(), e.getY(), 25, 25, ColorPalette.ERASER_COLOR, true));
                    repaint();
                }
            }
        });
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); // هذا السطر ضروري جداً لظهور الأزرار
        for (GraphicShape s : shapesList) {
            s.render(g);
        }
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PaintProject().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
