
import java.awt.Color;
import java.awt.Graphics;

public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    public NewJFrame() {
        initComponents();
    }

    @Override
    public void paint(Graphics g){
        super.paint(g);
        g.drawOval(100, 50, 200, 50);
        g.setColor(Color.YELLOW);
        g.fillOval(101, 50, 198, 48);
        
        g.setColor(Color.BLACK);
        g.drawArc(80, 175, 240, 50, 0, -180);
        
        g.setColor(Color.BLACK);
        g.drawLine(100, 75, 80, 200);
        g.drawLine(300, 75, 320, 200);
        
        g.setColor(Color.yellow);
        g.fillOval(175, 110, 50, 100);
        g.fillOval(100, 125, 50, 60);
        g.fillOval(250, 125, 50, 60);
        
        g.setColor(Color.BLACK);
        g.drawLine(190, 223, 180, 275);
        g.drawLine(210, 223, 220, 275);
        g.drawRect(125, 275, 150, 20);
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
